### ISSUE TITLE
ssl.SSLError: [SSL: CA_KEY_TOO_SMALL] using UWCA root cert

### ISSUE THREAD

**Issue by nhoffman** [nhoffman/uwgroups#3]
On ubuntu and debian systems:

```python
"""
Minimal test of a connection to the UW Groups API

A file containig cert + key must be provided as the first argument
"""

from tempfile import NamedTemporaryFile
import http.client
import json
import sys

ROOT_CERT = """
-----BEGIN CERTIFICATE-----
MIIEBzCCA3CgAwIBAgIBADANBgkqhkiG9w0BAQQFADCBlDELMAkGA1UEBhMCVVMx
CzAJBgNVBAgTAldBMSEwHwYDVQQKExhVbml2ZXJzaXR5IG9mIFdhc2hpbmd0b24x
FDASBgNVBAsTC1VXIFNlcnZpY2VzMRcwFQYDVQQDEw5VVyBTZXJ2aWNlcyBDQTEm
MCQGCSqGSIb3DQEJARYXaGVscEBjYWMud2FzaGluZ3Rvbi5lZHUwHhcNMDMwMjI1
MTgyNTA5WhcNMzAwOTAzMTgyNTA5WjCBlDELMAkGA1UEBhMCVVMxCzAJBgNVBAgT
AldBMSEwHwYDVQQKExhVbml2ZXJzaXR5IG9mIFdhc2hpbmd0b24xFDASBgNVBAsT
C1VXIFNlcnZpY2VzMRcwFQYDVQQDEw5VVyBTZXJ2aWNlcyBDQTEmMCQGCSqGSIb3
DQEJARYXaGVscEBjYWMud2FzaGluZ3Rvbi5lZHUwgZ8wDQYJKoZIhvcNAQEBBQAD
gY0AMIGJAoGBALwCo6h4T44m+7ve+BrnEqflqBISFaZTXyJTjIVQ39ZWhE0B3Laf
bbZYju0imlQLG+MEVAtNDdiYICcBcKsapr2dxOi31Nv0moCkOj7iQueMVU4E1Tgh
YIR2I8hqixFCQIP/CMtSDail/POzFzzdVxI1pv2wRc5cL6zNwV25gbn3AgMBAAGj
ggFlMIIBYTAdBgNVHQ4EFgQUVdfBM8b6k/gnPcsgS/VajliXfXQwgcEGA1UdIwSB
uTCBtoAUVdfBM8b6k/gnPcsgS/VajliXfXShgZqkgZcwgZQxCzAJBgNVBAYTAlVT
MQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9u
MRQwEgYDVQQLEwtVVyBTZXJ2aWNlczEXMBUGA1UEAxMOVVcgU2VydmljZXMgQ0Ex
JjAkBgkqhkiG9w0BCQEWF2hlbHBAY2FjLndhc2hpbmd0b24uZWR1ggEAMAwGA1Ud
EwQFMAMBAf8wKwYDVR0RBCQwIoYgaHR0cDovL2NlcnRzLmNhYy53YXNoaW5ndG9u
LmVkdS8wQQYDVR0fBDowODA2oDSgMoYwaHR0cDovL2NlcnRzLmNhYy53YXNoaW5n
dG9uLmVkdS9VV1NlcnZpY2VzQ0EuY3JsMA0GCSqGSIb3DQEBBAUAA4GBAIn0PNmI
JjT9bM5d++BtQ5UpccUBI9XVh1sCX/NdxPDZ0pPCw7HOOwILumpulT9hGZm9Rd+W
4GnNDAMV40wes8REptvOZObBBrjaaphDe1D/MwnrQythmoNKc33bFg9RotHrIfT4
EskaIXSx0PywbyfIR1wWxMpr8gbCjAEUHNF/
-----END CERTIFICATE-----"""


with NamedTemporaryFile('w+') as root_cert:

    if len(sys.argv) > 1 and sys.argv[1]:
        certfile = sys.argv[1]
    else:
        sys.exit('specify path to file containing cert+key')

    root_cert.write(ROOT_CERT)
    root_cert.seek(0)

    context = http.client.ssl.create_default_context()
    context.load_cert_chain(certfile=certfile)
    context.load_verify_locations(root_cert.name)
    # uncomment to fix error
    # context.set_ciphers('DEFAULT@SECLEVEL=1')

    connection = http.client.HTTPSConnection(
        host='dev.groups.uw.edu',
        timeout=60,
        port=443,
        context=context)

    connection.request(
        'GET', '/group_sws/v3/group/u_labmed_div_informatics',
        headers={'accept': 'application/json'})

    response = connection.getresponse()
    print(response.status)
    # print(json.loads(response.read().decode()))
```

```
docker run --rm -it -v "$(pwd):$(pwd)" -w "$(pwd)" python:3.9-slim-buster python3 test-uwgroups.py 2022-06-28-new-cert/elmira.cert
Traceback (most recent call last):
  File "/Users/nhoffman/src/userbase/test-uwgroups.py", line 65, in <module>
    response = connection.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: CA_KEY_TOO_SMALL] ca key too small (_ssl.c:2633)
```

Add ``context.set_ciphers('DEFAULT@SECLEVEL=1')`` to work around until root cert is updated.

**Comment by nhoffman** [comment]
fixed in tag 0.3.6
